from . import secret as secret

ENV = {
    "DATABASE_NAME": secret.DATABASE_NAME,
    "DATABASE_USER": secret.DATABASE_USER,
    "DATABASE_PASSWORD": secret.DATABASE_PASSWORD,
    "DATABASE_HOST": secret.DATABASE_HOST,
    "DATABASE_PORT": secret.DATABASE_PORT,
    "DEBUG_MODE": secret.DEBUG_MODE,
    "ALLOWED_HOSTS": secret.ALLOWED_HOSTS,
    "GRAPHIQL_MODE": secret.GRAPHIQL_MODE,
    "SELLARTS_KEY": secret.SELLARTS_KEY,
    "ANKA_TOKEN": secret.ANKA_API_TOKEN,
    "REQUIRED_AUTHENTICATION": secret.REQUIRED_AUTHENTICATION,
}
