import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "SellArts",
  description: "Generated by create next app",
};

import "./globals.css";
import ClientWrapper from "./[locale]/clientWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`} cz-shortcut-listen="true">
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
